#!/bin/sh

case "$1" in
	start)
		echo "Starting scull and misc-modules"
		modprobe hello
		module_load faulty
		scull_load
		;;
	stop)
		echo "Stopping scull and misc-modules"
		scull_unload
		module_unload faulty
		modprobe -r hello
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
