#!/bin/sh

case "$1" in
	start)
		echo "Starting aesdsocket"
		start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- -d
		aesdchar_load
		;;
	stop)
		echo "Stopping aesdsocket"
		killall -TERM aesdsocket
		aesdchar_unload
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
